#!/usr/bin/env node
// Stamps the deploy SHA into JSX <script src> tags in the public HTML files
// so every deploy invalidates the Cloudflare edge + browser cache of those
// files. Runs as part of `npm run deploy`, which Cloudflare Workers Builds
// executes on every push to main. Without this, edge-cached JSX persists
// past the deploy and users see stale UI for hours.
//
// Hash source priority:
//   WORKERS_CI_COMMIT_SHA   (Cloudflare Workers Builds)
//   GITHUB_SHA              (GitHub Actions, if we ever re-add one)
//   `git rev-parse HEAD`    (local fallback for manual `wrangler deploy`)
//   timestamp               (last-resort fallback so we always stamp something)

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { precompileTree } = require('./precompile-jsx.js');

// Regenerate the per-brand rules in public/_headers by scanning for blueprint
// dirs (any dir with both index.html and a components/ subdir — brands +
// demo/blueprint). Each gets: HTML + components revalidate, assets immutable.
// Replaces the marked block, so adding a blueprint never needs a manual edit.
const BRAND_START = '# >>> AUTO BRAND RULES (generated by scripts/stamp-deploy.js — do not edit by hand)';
const BRAND_END = '# <<< AUTO BRAND RULES';
function findBrandDirs(publicDir, rel = '', out = []) {
  for (const e of fs.readdirSync(path.join(publicDir, rel), { withFileTypes: true })) {
    if (!e.isDirectory()) continue;
    const childRel = rel ? `${rel}/${e.name}` : e.name;
    const childAbs = path.join(publicDir, childRel);
    if (fs.existsSync(path.join(childAbs, 'index.html')) && fs.existsSync(path.join(childAbs, 'components'))) {
      out.push(childRel);
    } else {
      findBrandDirs(publicDir, childRel, out);
    }
  }
  return out;
}
function regenBrandHeaders(publicDir) {
  const headersPath = path.join(publicDir, '_headers');
  const brands = findBrandDirs(publicDir).sort();
  // Cloudflare hard-caps _headers at 100 rules and FAILS THE DEPLOY above it,
  // so each brand gets exactly two: the HTML (its URL never changes, so it
  // must revalidate for deploys to roll out) and the assets (byte-stable).
  // Everything else a brand page loads is ?v=DEPLOY_HASH-busted and needs no
  // rule for correctness.
  const block = brands.map((b) => (
    `/${b}/\n  Cache-Control: public, max-age=0, must-revalidate\n` +
    `/${b}/assets/*\n  Cache-Control: public, max-age=31536000, immutable`
  )).join('\n');
  const src = fs.readFileSync(headersPath, 'utf8');
  const s = src.indexOf(BRAND_START);
  const e = src.indexOf(BRAND_END);
  if (s === -1 || e === -1) return 0; // markers missing — leave file untouched
  const next = `${src.slice(0, s)}${BRAND_START}\n${block}\n${src.slice(e)}`;
  if (next !== src) fs.writeFileSync(headersPath, next);
  return brands.length;
}

function resolveSha() {
  if (process.env.WORKERS_CI_COMMIT_SHA) return process.env.WORKERS_CI_COMMIT_SHA;
  if (process.env.GITHUB_SHA) return process.env.GITHUB_SHA;
  try {
    return execSync('git rev-parse HEAD', { encoding: 'utf8' }).trim();
  } catch (_) {
    return 't' + Date.now().toString(36);
  }
}

function main() {
const sha = resolveSha().slice(0, 8);
// Stamp every HTML file in the tree that carries a DEPLOY_HASH token — the
// same walk precompile-jsx uses, so a new page can never be silently left
// un-versioned by a stale manual list (the old hardcoded array's failure
// mode).
const { findHtml } = require('./precompile-jsx.js');
const files = findHtml('public');

let touched = 0;
for (const f of files) {
  const before = fs.readFileSync(f, 'utf8');
  if (!before.includes('DEPLOY_HASH')) continue;
  fs.writeFileSync(f, before.replace(/DEPLOY_HASH/g, sha));
  touched++;
}
console.log(`[stamp-deploy] sha=${sha} files-rewritten=${touched}`);

// Precompile JSX → JS on real deploys only (Cloudflare Workers Builds sets
// WORKERS_CI_COMMIT_SHA). Locally we leave the source as .jsx + in-browser
// Babel so `wrangler dev` and direct editing keep working. In CI we transpile
// ahead of time and drop the 3MB Babel runtime from the deployed bundle, so
// production pages ship plain .js with no in-browser transpile.
// Brand cache rules are cheap + deterministic; regenerate on every run so
// public/_headers always matches the brands on disk (fixes stale-after-deploy).
const brandCount = regenBrandHeaders('public');
console.log(`[stamp-deploy] _headers brand rules regenerated for ${brandCount} blueprint dirs`);
// Cloudflare rejects deploys with more than 100 _headers rules, so fail loud
// here (where the message is readable) instead of at version upload.
const ruleCount = fs.readFileSync('public/_headers', 'utf8').split('\n').filter((l) => l.startsWith('/')).length;
console.log(`[stamp-deploy] _headers rules total=${ruleCount} (Cloudflare limit 100)`);
if (ruleCount > 100) throw new Error(`_headers has ${ruleCount} rules — over Cloudflare's 100-rule limit; trim rules or drop per-brand entries`);
if (ruleCount > 90) console.warn(`[stamp-deploy] WARNING: _headers at ${ruleCount}/100 rules — nearing Cloudflare's hard limit`);

const isCI = !!(process.env.WORKERS_CI_COMMIT_SHA || process.env.GITHUB_SHA || process.env.PRECOMPILE_JSX);
if (isCI) {
  const { pages, files } = precompileTree('public');
  let droppedBabel = false;
  try { fs.unlinkSync('public/vendor/babel.min.js'); droppedBabel = true; } catch (_) {}
  console.log(`[stamp-deploy] precompiled pages=${pages} jsx-files=${files} dropped-babel=${droppedBabel}`);
} else {
  console.log('[stamp-deploy] precompile skipped (not a CI deploy)');
}
}

module.exports = { regenBrandHeaders, findBrandDirs };
if (require.main === module) main();
